MAX_FAILED_LOGINS = 5
LOCK_TIME_MINUTES = 2
SESSION_LIFETIME_MINUTES = 30
SESSION_RESUME_MINUTES = 5

TIMESTAMP_TOLERANCE_SECONDS = 30
REQUEST_HISTORY_TTL_SECONDS = 300

RATE_LIMIT_PER_SECOND = 10
RATE_LIMIT_PER_MINUTE = 100
RATE_LIMIT_BAN_SECONDS = 180
RATE_LIMIT_MAX_VIOLATIONS = 3
RATE_LIMIT_VIOLATION_WINDOW_SECONDS = 120
